name: Deploy La Rue ASBL
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.O2SWITCH_SERVER }}
          username: ${{ secrets.O2SWITCH_USERNAME }}
          password: ${{ secrets.O2SWITCH_PASSWORD }}
          server-dir: /web-applications/fakes/larueasbl.cyber-forge-development.com/
